steps:
 - label: "Ubuntu 14.04"
   command: ".buildkite/presubmit.sh"
   agents:
     - "os=ubuntu1404"

 - label: "Ubuntu 16.04"
   command: ".buildkite/presubmit.sh"
   agents:
     - "os=ubuntu1604"
